name: Deploy to GH Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Node.js
        uses: actions/setup-node@v2.2.0
        with:
          cache: npm
          node-version: 14.x
      - name: Install
        run: npm i -g npm@8 && npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          allow_empty_commit: true
          cname: 'ghpages'
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
